hopper:
  build: .
  environment: 
    - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    - SECRET_KEY=${SECRET_KEY}
    - DEBUG=${DEBUG}
  volumes:
    - .:/home/hopper/code
  command: ./bin/run
  ports:
      - 8000:8000
