# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopper', '0005_auto_20161225_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='conbook_desc',
            field=models.TextField(default=b''),
        ),
        migrations.AddField(
            model_name='event',
            name='requirements',
            field=models.TextField(default=b''),
        ),
    ]
