# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopper', '0007_event_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='conbook_desc',
            new_name='guidebook_desc',
        ),
        migrations.AddField(
            model_name='event',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='runners',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='size',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
