# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopper', '0010_auto_20170108_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('colour', models.CharField(max_length=40)),
            ],
        ),
    ]
