# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 14:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hopper', '0011_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='trackId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hopper.Track'),
        ),
    ]
