# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 14:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hopper', '0012_event_trackid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='trackId',
            new_name='track',
        ),
    ]
