# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-08 18:50
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('hopper', '0013_auto_20170108_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='badges',
            field=models.TextField(blank=True, default=b'', validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AddField(
            model_name='event',
            name='online_desc',
            field=models.TextField(blank=True, default=b''),
        ),
    ]
