# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-08 18:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('hopper', '0014_auto_20170208_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='badges',
            field=models.CharField(blank=True, default=b'', max_length=300, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AlterField(
            model_name='event',
            name='runners',
            field=models.CharField(blank=True, default=b'', max_length=300),
        ),
    ]
