# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-14 20:39
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hopper', '0017_event_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCompleted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('desc', models.TextField(blank=True, default=b'')),
                ('requirements', models.TextField(blank=True, default=b'')),
                ('internal', models.TextField(blank=True, default=b'')),
                ('runners', models.CharField(blank=True, default=b'', max_length=300)),
                ('badges', models.CharField(blank=True, default=b'', max_length=300, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('event_organiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('resourceId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hopper.Room')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hopper.Track')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='event',
            name='last_confirmed',
        ),
        migrations.RemoveField(
            model_name='event',
            name='last_modified',
        ),
    ]
