# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-15 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hopper', '0018_auto_20171014_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='complete_copy',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='hopper.EventCompleted'),
        ),
    ]
