# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-18 21:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hopper', '0019_event_complete_copy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='complete_copy',
            new_name='event_completed',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_organiser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventcompleted',
            name='event_organiser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
