# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-21 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hopper', '0020_auto_20171018_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_completed',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hopper.EventCompleted'),
        ),
    ]
