# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-21 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopper', '0021_auto_20171021_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='eventcompleted',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
